/lightwarelidar/sf45b:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    frame_id: "laser"
    publish_laser_scan: true
    updateRate: 6 #12
    cycleDelay: 5
    lowAngleLimit: -35.0
    highAngleLimit: 35.0
    maxPoints: 100

/**:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    frame_id: "laser"
    publish_laser_scan: true
    updateRate: 6 #12
    cycleDelay: 5
    lowAngleLimit: -35.0
    highAngleLimit: 35.0
    maxPoints: 100
